apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
    - name: tomcat-port
      protocol: TCP
      port: 8081
      targetPort: tomcat-port
  selector:
    app: mp
  type: ClusterIP
  sessionAffinity: None
