apiVersion: v1
kind: ConfigMap
metadata:
  name: login-page-map
  namespace: mp-demo
data:
  PageLogin.html: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      ~ Copyright (c) 2010-2013 Evolveum
      ~
      ~ This work is dual-licensed under the Apache License 2.0
      ~ and European Union Public License. See LICENSE file for details.
      -->

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
            "http://www.w3.org/TR/html4/loose.dtd">
    <html xmlns:wicket="http://wicket.apache.org">

    <body>
        <wicket:extend>
            <form method="post" class="form-horizontal" wicket:id="form">
                <!-- begin changes -->
                <div class="form-group">
                    <div class="col-md-4 col-lg-12 text-center">
                        <a href="https://wiki.evolveum.com/display/midPoint/Live+Demo" target="_blank">Live demo documentation</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-lg-12 text-center">
                        Demo credentials: <strong>administrator</strong> / <strong>5ecr3t</strong>
                    </div>
                </div>
                <!-- end changes -->
                <div class="form-group">
                    <label class="col-md-4 col-lg-4 control-label">
                    <wicket:message key="PageLogin.username"/>
                </label>

                    <div class="col-md-8 col-lg-8">
                        <input name="username" type="text" class="form-control input-sm focus-username" wicket:message="placeholder:PageLogin.username">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 col-lg-4 control-label">
                    <wicket:message key="PageLogin.password"/>
                </label>

                    <div class="col-md-8 col-lg-8">
                        <div class="password-parent" style="height:30px; position: relative;">
                            <div class="col-md-12" style="padding: 0px !important;">
                                <input name="password" type="password" class="form-control input-sm" wicket:message="placeholder:PageLogin.password" style="padding-right: 26px;">
                            </div>
                            <div style="position: absolute; right: 8px; top: 8px; z-index: 5;">
                                <i class="fa fa-eye" style="float:right;cursor: pointer; color: #555555;" onclick="showPassword(this)"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div wicket:id="csrfField" />

                <wicket:link>
                    <a class="btn" role="button" href="forgetpassword" wicket:id="forgetpassword">
                        <wicket:message key="PageLogin.forgetPassword" />
                    </a>
                </wicket:link>

                <div class="pull-right">
                    <a class="btn btn-default" role="button" wicket:id="selfRegistration">
                        <wicket:message key="PageLogin.selfRegistration" />
                    </a>

                    <input type="submit" class="btn btn-primary" wicket:message="value:PageLogin.signIn" />
                </div>
            </form>
        </wicket:extend>

    </body>

    </html>
  addLoginPage.sh: |
    #!/bin/bash
    cp /opt/midpoint/lib/* /mnt/lib/
    cd /mnt/lib
    unzip -q midpoint.war -d midpoint2
    cd midpoint2/WEB-INF/classes/com/evolveum/midpoint/web/page/login/
    cp /mnt/page/PageLogin.html .
    cd /mnt/lib
    rm midpoint.war
    apk add zip
    cd midpoint2
    zip -0 -r midpoint.war .
    mv midpoint.war /mnt/lib/
    cd ..
    rm -rf midpoint2

