apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tomcat
spec:
  template:
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            server: nfs-service.testdemo.svc.cluster.local
            path: /

