apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-hr-db
  namespace: mp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-hr-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-hr-db
    spec:
      volumes:
        - name: sql-script
          configMap:
            name: hr-script-map
            defaultMode: 420
      containers:
        - name: hr-db
          image: 'postgres:13-alpine'
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_INITDB_ARGS
              value: '--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8'
            - name: POSTGRES_USER
              value: midpoint
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mp-secret
                  key: password
          resources: {}
          volumeMounts:
            - name: sql-script
              mountPath: /docker-entrypoint-initdb.d
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: hr-service
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

