apiVersion: v1
kind: Pod
metadata:
  name: mp-demo-cert
  namespace: mp-demo
spec:
  volumes:
    - name: vol
      emptyDir: {}
  initContainers:
    - name: mp-config-init
      image: evolveum/midpoint:4.4.1-alpine
      command:
        - /bin/bash
        - /opt/midpoint/bin/midpoint.sh
        - init-native
      env:
        - name: MP_PW_DEF
          value: /opt/mp-home/keystorepw
        - name: MP_KEYSTORE
          value: /opt/mp-home/keystore.jceks
        - name: MP_CERT
          valueFrom:
            secretKeyRef:
              name: cert-mp-pg-demo
              key: tls.crt
      volumeMounts:
        - name: vol
          mountPath: /opt/mp-home
          subPath: mp-home
      imagePullPolicy: IfNotPresent
  containers:
    - name: mp-demo-cert
      image: evolveum/midpoint:4.4.1-alpine
      ports:
        - name: gui
          containerPort: 8080
          protocol: TCP
      env:
        - name: MP_NO_ENV_COMPAT
          value: '1'
      volumeMounts:
        - name: vol
          mountPath: /opt/midpoint/var
          subPath: mp-home
      imagePullPolicy: IfNotPresent
  restartPolicy: Always