= Kubernetes - advanced examples
:toc:
:toclevels: 4

This location contain files related to the documentation page - https://docs.evolveum.com/midpoint/install/kubernetes/advanced-examples/ .

[WARNING]
We will handle advance configuration of the environment.
The goal is to show how it can be realized in the kubernetes environments.
The prerequisite for the scenario is only default objects imported during the first system start.
The objects are stored in the repository after the changes are applied.
Once the system is set up and running we should not re-apply the changes if we don't explicitly want to do that.
In some situation adding another the same labeled block of the setting may lead to conflict with schema and failure of the system.

== complex example

=== Start environent

.environment with local home
[source]
----
# start environment
kubectl apply -f ../base-environment/namespace-mp-demo.yaml -f ../base-environment/secret-pw.yaml -f ../base-environment/service-db.yaml -f ../base-environment/statefulset-db-pg-native-pv.yaml -f configmap-poi-111-sysconf-deployment.yaml -f configmap-poi-120-flexible-auth.yaml -f configmap-poi-role_user_org_task.yaml -f configmap-poi-ldap-res.yaml -f service-nfs.yaml -f statefulset-nfs.yaml -f service-ldap.yaml -f configmap-ldap-init.yaml -f statefulset-ldap.yaml  -f statefulset-pg-native_cm-sec-nfs.yaml -f service-midpoint.yaml -f secret-cert-mp-pg-demo.yaml -f ingress-midpoint.yaml
----

.environment with shared home (NFS) - log saved to subfolder per MP node
[source]
----
# start environment
kubectl apply -f ../base-environment/namespace-mp-demo.yaml -f ../base-environment/secret-pw.yaml -f ../base-environment/service-db.yaml -f ../base-environment/statefulset-db-pg-native-pv.yaml -f configmap-poi-111-sysconf-deployment.yaml -f configmap-poi-120-flexible-auth.yaml -f configmap-poi-role_user_org_task.yaml -f configmap-poi-ldap-res.yaml -f service-nfs.yaml -f statefulset-nfs.yaml -f service-ldap.yaml -f configmap-ldap-init.yaml -f statefulset-ldap.yaml  -f statefulset-pg-native_cm-sec-nfs_home.yaml -f service-midpoint.yaml -f secret-cert-mp-pg-demo.yaml -f ingress-midpoint.yaml
----


=== Check the objects

[source]
----
# get the list of objects
kubectl get -n mp-demo ingress,secret,service,statefulset,configmap
----

=== Clean up the objects

[WARNING]
This will delete the objects from the kubernetes environment!

[source]
----
# remove created objects (without persistent volumes)
kubectl delete -n mp-demo ingress/mp-pg-demo secret/cert-mp-pg-demo service/mp-pg-demo statefulset/mp-pg-demo statefulset/mp-demo-ldap configmap/mp-demo-ldap-init service/mp-demo-ldap statefulset/mp-demo-nfs service/mp-demo-nfs configmap/mp-demo-poi-ldap-res configmap/mp-demo-poi-role-user-org-task configmap/mp-demo-poi-120-flexible-auth configmap/mp-demo-poi-111-sysconf-deployment statefulset/mp-demo-db service/mp-demo-db secret/mp-demo

# remove also peristent volumes
kubectl delete -n mp-demo pvc/mp-demo-ldap-store-mp-demo-ldap-0 pvc/mp-demo-nfs-store-mp-demo-nfs-0 pvc/mp-demo-pg-storage-mp-demo-db-0
----

== Cheat sheet

There may be few useful commands for daily working...

=== basic handling

.create / modify the object using the yaml file
[source,bash]
kubectl apply -f configmap-poi.yaml

.destroy the pods ("power off" midpoint environment)
[source,bash]
kubectl scale -n mp-demo --replicas=0 statefulset/mp-pg-demo statefulset/mp-demo-db

.get the list of pods and statefulsets in the mp-demo namespace
[source,bash]
kubectl get -n mp-demo pods 
kubectl get -n mp-demo statefulsets

.create the pods ("power on" midpoint environment)
[source,bash]
kubectl scale -n mp-demo --replicas=1 statefulset/mp-pg-demo statefulset/mp-demo-db

.show the log from midpoint container mp-pg-demo in the pod mp-pg-demo-0 ( "follow" the new records of the log)
[source,bash]
kubectl logs -n mp-demo -f mp-pg-demo-0 -c mp-pg-demo

.Run sheel in the midpoint container
[source,bash]
kubectl exec -ti -n mp-demo mp-pg-demo-0 -c mp-pg-demo -- /bin/bash

=== Clustered nodes - scaling

.to run 3 node midpoint cluster
[source]
kubectl scale -n mp-demo --replicas=3 statefulset/mp-pg-demo

