= Kubernetes - advanced examples
:toc:
:toclevels: 4

This location contain files related to the dokumentation page - https://docs.evolveum.com/midpoint/install/kubernetes/advanced-examples/ .

[WARNING]
We will handle advanced configuration of the environment.
The goal is to show how it can be realized in the kubernetes environments.
The prerequisite for the scenario is only default objects imported during the first system start.
The objects are stored in the repository after the changes are applied.
Once the system is set up and running we should not re-apply the changes if we don't explicitly want to do that.
In some situation adding another the same labeled block of the setting may lead to conflict with schema and failure of the system.

== Basic handling

For the base operation the small "cheat sheat" may be useful.

.create / modify the object using the yaml file
[source,bash]
kubectl apply -f configmap-poi.yaml

.destroy the pods ("power off" midpoint environment)
[source,bash]
kubectl scale -n mp-demo --replicas=0 statefulset/mp-pg-demo statefulset/mp-demo-db

.get the list of pods and statefulsets in the mp-demo namespace
[source,bash]
kubectl get -n mp-demo pods 
kubectl get -n mp-demo statefulsets

.create the pods ("power on" midpoint environment)
[source,bash]
kubectl scale -n mp-demo --replicas=1 statefulset/mp-pg-demo statefulset/mp-demo-db

.show the log from midpoint container mp-pg-demo in the pod mp-pg-demo-0 ( "follow" the new records of the log)
[source,bash]
kubectl logs -n mp-demo -f mp-pg-demo-0 -c mp-pg-demo

.Run sheel in the midpoint container
[source,bash]
kubectl exec -ti -n mp-demo mp-pg-demo-0 -c mp-pg-demo -- /bin/bash

== Customization

=== Deployment information @ System configuration

.Re-aply the configuration : create or update based on current state of the object
[source]
kubectl apply -f statefulset-pg-native_cm-sec.yaml

.Changing mount point for Post-init-objects to prevent their re-apply with new pod
[source]
kubectl scale -n mp-demo --replicas=0 statefulset/mp-pg-demo
sed "s|/opt/midpoint-dirs-docker-entrypoint/post-initial-objects|/opt/midpoint-dirs-docker-entrypoints/post-initial-objects|" statefulset-pg-native_cm-sec.yaml | kubectl apply -f -
kubectl scale -n mp-demo --replicas=1 statefulset/mp-pg-demo

[TIP]
The scaling related steps are optional as the changes on the statefulset definition will cause recreating of the pods.

[NOTE]
Be aware of the persistency of the keystore to not lost the access to already encrypted fields in the repository.

=== Secret object with keystore object

[source]
keytool -genseckey -alias default -keystore keystore.jceks -storetype jceks -keyalg AES -keysize 128 -storepass changeit -keypass midpoint

.Create the secert object from the file
[source]
kubectl create secret generic -n mp-demo mp-demo-keystore --from-file keystore.jceks --from-literal=keystore=changeit

.Delete the secret object
[source]
kubectl delete secret -n mp-demo mp-demo-keystore

==== Clustered nodes

.to run 3 node midpoint cluster
[source]
kubectl scale -n mp-demo --replicas=3 statefulset/mp-pg-demo

