apiVersion: v1
kind: Secret
metadata:
  name: cert-mp-pg-demo
  namespace: mp-demo
stringData:
  Expiration: Feb 20 09:04:53 2032 GMT
  SAN: DNS:mp-pg-demo.mp-demo.local, DNS:www.mp-pg-demo.mp-demo.local, DNS:localhost, DNS:localhost.localdomain, IP Address:127.0.0.1
data:
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRQzdpVGs3T2hsMEc0R1YKenBsV25lN0NHSkNMYXg5RkU5VHgz
    Tk1CTnZyTTM5YnNXZmVZR2VDTWRGOG9vMEZ5WXFDZVVnRHZtck9LSXA3RAp2bjltS3puU1JQbVhG
    TnhMZDlYS1VGK1EwVTdWWkE2cURRVWtFeWdZOTJzcEhIRER4ZHNBSGw5T0ZJMGQ3bG1WCmpSR0VW
    ZnZGWklBUE1EdGZnWE1heTZpN3FYWEdHdE13Mjd4dXQ5U2Qvb2xZYlRYMloxNjl5V0ZuTXJKd0Ji
    dlIKUjJFQTVpUHRyY3M4ekVaNi91MHRBSURia3NJdlFaMk45bWRuT1NUS0ZoQnVxUlNhM3JBQXFa
    TjZ3WGNEUHk1YgpzVXBZaG4yUXVTdGRVL3ZHK0lZanVCcjVkaXRZejVEWG5YbDV4UmN2ZGlZNE9m
    OVowVnZBWktjQmVYMlpBakptClkxRUN3ZTVMQWdNQkFBRUNnZ0VBQ0VkRmRIemJGTW9HRFdQaVZ2
    Vi96YWVoOGRXWHVzZm1WWXJtOFozSXNuU0wKRzBIWmNTaHJSaWY0NzJWTmhVd2ZSUDNmdHJRQWl1
    OStUS3ZER2ZKOGlmQ3JoK1RPMkxJQWlQN0ZTVEpFSloxVwpIR0dZd1gvcS9EY256dGZIam96VVh3
    djRMdzB2TVl3TS9sSU0zT2VpeHBMcUtFRjd6WHA4WjBsb09HaUJuMjRLClZsL0wwb3dDVzc4bFNy
    ME9BcU5KN1krWDQ5aGQ4T05KdlYwSUtZQm5MbEVIUGQwSysxL3ZsdmJQNkMwSS9TNkkKYXZ0MXlu
    bHQ2MVV1eEVCZzVUQTZHWEJnQ2Y2N01sWWMyRDJoSHJjaDNMdlY1bjVocVdTaXNJblpiR0xNSTdD
    cgoycW1uSDB1QlpqR0FLaG5xNHdWUDZSVmJDRSsrejYxTHMrMDd5dS9Eb1FLQmdRRG41NDlYaDdE
    dlV4WnZIS3hECjlURi9yNmlHeXIyY3VsN0tpOThYTUFZdXFsQmwxVDNNMTB4UnQzNGdYbTBOSjZs
    a0xjRUhxTEhsdWZPQ3U4MlMKMzZ3NmYwd1NMYUo3ckJlZlNOK3EyNmFObVlkcW9iclZQUWc1R0ti
    Q1E3UWYvOTViMTc5S3V5UFpEdDQvQTJUZwowQ294S1FVWUVnd1hXRWowTUJmQ3R3RlEyd0tCZ1FE
    UEJZRHdnaW55SlNwZ3JtZkZLdk4wUXYrNEQ3eUR4SllwCmxNMTVTWnpwUU41ZFJlZkdVcVlMZnRx
    R0dSSWk2aFRhU3VTeEVtV1Y1R21EWlQxR1RmMkVVQWpkNnIyM0JVWS8KcXMxQlRmUDVMaXhNaEZz
    YkRoMlpxT0tnb1pBVy9DSXVtVU9GcFZyVkIwdFQvc0lZV1ZIMUJTcEhCZFczdHRqNgpKTjVMMDBU
    YlVRS0JnUURRNWFNV3l0RlVWRGtpTCtieGRINTVNYWVTZkRDZmJMYVVwN2gzTDdoeDh0Tm5WOVpL
    Cm5pcE9kZ2IwYTNxNlhkN1ZzZTF1MDhRa1Z3UUc0TnVHa1Z1WWVqRHhNeEJwYlJUK1UrdS9BZ3Vm
    QkF5YXZrTUoKY09mbVh0RmdyeElqdlIzMUIzeDJlZXNKekwzZ2IxTkF1K00xMDJpV1RUTjlGL2Ju
    bUNiZkxIRFAvd0tCZ1FDaQp6REF1Y2gyc1J4L0JNY1YyM3FUZXE0Vk82RWtWMGZWSU03VTFpUGIw
    MHNkSzBCdEk4VnVVTktpQnhadG1pMi9rCmpmcXphTVVzRDVnTjlRSXZsRXNsem81NmZRdTlyazhr
    NkJ0TEhKTWNRL3dnSEFGTkVGZWtxNU8wUC9rQXFqdnoKS3lGWEtzWjRPYWs2SDEvaEovUjBXeUI1
    QTVTaVNRN3QveW8wdEtvMFVRS0JnRXlKMDAzYVZjK2MxSHhHaTNEWApKZDUyL1d5YXVvemZhQVFx
    djd4UE9EdXNOSGdmRStIS3pyNHZpckcxbkVNaWE3ZTZldEtLeW9YRldmT3RBTmZNCnBnODZYUEhO
    QmJnR3lYTjY1YVhvdHdqbHVXSXhCVkU5QkVRRGRKZjBRd3JvaGpnTkZIUm1sUzlYL05UZWQ4YWUK
    QmdlazlZdlBOOHd5WTFkSzNSOVB2TTZPCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVZkltdTZIUTE0
    NXNPbjFyYTZwWW45S2dJUXprd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pa
    R1Z0YnlCalpYSjBNQjRYRFRJeU1ESXlNakE1TURRMU0xb1hEVE15TURJeQpNREE1TURRMU0xb3dG
    REVTTUJBR0ExVUVBd3dKWkdWdGJ5QmpaWEowTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NB
    UThBTUlJQkNnS0NBUUVBdTRrNU96b1pkQnVCbGM2WlZwM3V3aGlRaTJzZlJSUFU4ZHpUQVRiNnpO
    L1cKN0ZuM21CbmdqSFJmS0tOQmNtS2dubElBNzVxemlpS2V3NzUvWmlzNTBrVDVseFRjUzNmVnls
    QmZrTkZPMVdRTwpxZzBGSkJNb0dQZHJLUnh3dzhYYkFCNWZUaFNOSGU1WmxZMFJoRlg3eFdTQUR6
    QTdYNEZ6R3N1b3U2bDF4aHJUCk1OdThicmZVbmY2SldHMDE5bWRldmNsaFp6S3ljQVc3MFVkaEFP
    WWo3YTNMUE14R2V2N3RMUUNBMjVMQ0wwR2QKamZablp6a2t5aFlRYnFrVW10NndBS21UZXNGM0F6
    OHVXN0ZLV0laOWtMa3JYVlA3eHZpR0k3Z2ErWFlyV00rUQoxNTE1ZWNVWEwzWW1PRG4vV2RGYndH
    U25BWGw5bVFJeVptTlJBc0h1U3dJREFRQUJvNElCRERDQ0FRZ3dDUVlEClZSMFRCQUl3QURBZEJn
    TlZIUTRFRmdRVVR0dVJIdGE4S0RuanVHenBWOEYwYy9uQXBtd3dUd1lEVlIwakJFZ3cKUm9BVVR0
    dVJIdGE4S0RuanVHenBWOEYwYy9uQXBteWhHS1FXTUJReEVqQVFCZ05WQkFNTUNXUmxiVzhnWTJW
    eQpkSUlVZkltdTZIUTE0NXNPbjFyYTZwWW45S2dJUXprd0N3WURWUjBQQkFRREFnWGdNR2tHQTFV
    ZEVRUmlNR0NDCkdHMXdMWEJuTFdSbGJXOHViWEF0WkdWdGJ5NXNiMk5oYklJY2QzZDNMbTF3TFhC
    bkxXUmxiVzh1YlhBdFpHVnQKYnk1c2IyTmhiSUlKYkc5allXeG9iM04wZ2hWc2IyTmhiR2h2YzNR
    dWJHOWpZV3hrYjIxaGFXNkhCSDhBQUFFdwpFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RFFZ
    SktvWklodmNOQVFFTEJRQURnZ0VCQUNYaHFRbEhkbk5GClhQNXJIR0JNOThQU0g3TVplYXZjUW5C
    RjNUNExEZ0NYZUkrK2FiNnNVcEZhSkFHZHgxNTZnZDZzTHI5T3lWNWgKTTJDbG9OVDBvbVhrSk9J
    MXVEQUp5cVV1OVJENDdOaUxEZjZ5cjl6OTF0NE8xcEF1NHJjV2FhS1Qvd3FWY0dkYQpXUTBtQmdO
    Z0pMVytUd3NUN3JuOTNtZGtoRUlWWHFtamhOTmQ2bmZEZGdrcG96WkNTUFFrZHQ4SWxsS2RQdnJD
    CkFxNHdCbERIektTSUlobkRGYTArMURVbkFBVFk5ZFJFQVJHUTVTTWpGZjJqNStrL21ySCt2cGtT
    eDdRRDByUXQKUms1YkRlNmdWZjZFMXhsNnM4ZTZVbjY1eG5jRjdrZW9EVURIVkhzNmQxNm5oZExB
    Mi95T01LU2RpYzJFYmZZQgo4V2pYSGJ0N085TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
type: kubernetes.io/tls
