apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: ConfigMap
    name: nfs-server-map
    fieldPath: data.nfs_server
  targets:
  - select:
      kind: StatefulSet
      name: mp
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
  - select:
      kind: StatefulSet
      name: tomcat
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
    
resources:
 - nfs-server-map.yaml
# NFS objects
 - objects/nfs/nfs-service.yml
 - objects/nfs/nfs-server.yml
# Certificate for ingresses
 - objects/certificates/cert-mp-demo.yml
# LDAP objects
 - objects/ldap/ldap-dynschema-map.yml
 - objects/ldap/ldap-init-map.yml
 - objects/ldap/ldap.yml
 - objects/ldap/ldap-service.yml
 - objects/ldap/ldap-admin-service.yml
 - objects/ldap/ldap-admin-ingress.yml
# Midpoint internal objects in config maps. These are extensions, post initial objects and initial hr resources.
 - objects/mp/mp-post-initial-object-map.yml
 - objects/mp/mp-hr-map.yml
 - objects/mp/users-map.yml
 - objects/mp/mp-extensions-map.yml
 - objects/mp/mp-login-page-map.yml
# MidPoint kubernetes objects
 - objects/mp/mp-secret.yml 
 - objects/mp/mp-db.yml
 - objects/mp/mp.yml
 - objects/mp/mp-db-service.yml
 - objects/mp/mp-ingress.yml
 - objects/mp/mp-service.yml
# Adressbook database initial script as config map
 - objects/addressbook/addressbook-script-map.yml
# Addressbook kubernetes objects
 - objects/addressbook/addressbook.yml
 - objects/addressbook/addressbook-service.yml
# HR database initial script in config map
 - objects/hr/hr-script-map.yml
# HR kubernetes objects
 - objects/hr/hr.yml
 - objects/hr/hr-service.yml
# Apache server kubernetes objects
 - objects/apache/apache-conf-map.yml
 - objects/apache/apache.yml
 - objects/apache/apache-ingress.yml
 - objects/apache/apache-service.yml
# Tomcat kubernetes objects
 - objects/tomcat/tomcat.yml
 - objects/tomcat/tomcat-service.yml
 - objects/tomcat/tomcat-hr-ingress.yml
 - objects/tomcat/tomcat-addressbook-ingress.yml
