apiVersion: v1
kind: Service
metadata:
  name: addressbook-db-service
  
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: addressbook-db
  type: ClusterIP
  sessionAffinity: None

