apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: remove
      path: /spec/tls/0/secretName
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress

resources:
  - ../../kustomize-base
  - network-policy.yml
