apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: mp-demo
spec:
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
  selector:
    app: demo-ldap
  type: ClusterIP
  sessionAffinity: None

