apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs
    spec:
      volumes:
        - name: nfs-share
          emptyDir: {}
      containers:
        - name: nfs-server-container
          image: 'itsthenetwork/nfs-server-alpine:12'
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          resources: {}
          volumeMounts:
            - name: nfs-share
              mountPath: /nfsshare
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: nfs-service
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

