apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: mp-demo
spec:
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetPort: 2049
  selector:
    app: nfs
  type: ClusterIP
  sessionAffinity: None

