apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.nfs_server
  targets:
  - select:
      kind: StatefulSet
      name: mp
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
  - select:
      kind: StatefulSet
      name: tomcat
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_host
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_cert
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls.0.secretName
    
resources:
 - config-files/options-map.yaml
# NFS base
 - base/nfs/nfs-service.yml
 - base/nfs/nfs-server.yml
# Certificate for ingresses
 - config-files/certificate/cert-mp-demo.yml
# LDAP base
 - base/ldap/ldap-dynschema-map.yml
 - base/ldap/ldap-init-map.yml
 - base/ldap/ldap.yml
 - base/ldap/ldap-service.yml
 - base/ldap/ldap-admin-service.yml
 - base/ldap/ldap-admin-ingress.yml
# Midpoint internal base in config maps. These are extensions, post initial base and initial hr resources.
 - base/mp/mp-post-initial-object-map.yml
 - base/mp/mp-hr-map.yml
 - base/mp/users-map.yml
 - base/mp/mp-extensions-map.yml
 - base/mp/mp-login-page-map.yml
# MidPoint kubernetes base
 - base/mp/mp-secret.yml 
 - base/mp/mp-db.yml
 - base/mp/mp.yml
 - base/mp/mp-db-service.yml
 - base/mp/mp-ingress.yml
 - base/mp/mp-service.yml
# Adressbook database initial script as config map
 - base/addressbook/addressbook-script-map.yml
# Addressbook kubernetes base
 - base/addressbook/addressbook.yml
 - base/addressbook/addressbook-service.yml
# HR database initial script in config map
 - base/hr/hr-script-map.yml
# HR kubernetes base
 - base/hr/hr.yml
 - base/hr/hr-service.yml
# Apache server kubernetes base
 - base/apache/apache-conf-map.yml
 - base/apache/apache.yml
 - base/apache/apache-ingress.yml
 - base/apache/apache-service.yml
# Tomcat kubernetes base
 - base/tomcat/tomcat.yml
 - base/tomcat/tomcat-service.yml
 - base/tomcat/tomcat-hr-ingress.yml
 - base/tomcat/tomcat-addressbook-ingress.yml
