apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.nfs_server
  targets:
  - select:
      kind: StatefulSet
      name: mp
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
  - select:
      kind: StatefulSet
      name: tomcat
    fieldPaths:
    - spec.template.spec.volumes.[name=nfs-volume].nfs.server
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_host
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_cert
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls.0.secretName
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_class_name
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.ingressClassName
    
resources:
 - kustomize-env-config/options-map.yaml
# LDAP base
 - kustomize-base/kubernetes-objects/ldap/ldap-admin-ingress.yml
 - kustomize-base/kubernetes-objects/ldap/ldap-service.yml
 - kustomize-base/kubernetes-objects/ldap/ldap.yml
 - kustomize-base/kubernetes-objects/ldap/ldap-admin-service.yml
# MidPoint kubernetes base
 - kustomize-base/kubernetes-objects/mp/mp-ingress.yml
 - kustomize-base/kubernetes-objects/mp/mp-service.yml
 - kustomize-base/kubernetes-objects/mp/mp-db.yml
 - kustomize-base/kubernetes-objects/mp/mp-secret.yml
 - kustomize-base/kubernetes-objects/mp/mp.yml
 - kustomize-base/kubernetes-objects/mp/mp-db-service.yml
# Addressbook kubernetes base
 - kustomize-base/kubernetes-objects/addressbook/addressbook-service.yml
 - kustomize-base/kubernetes-objects/addressbook/addressbook.yml
# HR kubernetes base
 - kustomize-base/kubernetes-objects/hr/hr.yml
 - kustomize-base/kubernetes-objects/hr/hr-service.yml
# Apache server kubernetes base
 - kustomize-base/kubernetes-objects/apache/apache.yml
 - kustomize-base/kubernetes-objects/apache/apache-ingress.yml
 - kustomize-base/kubernetes-objects/apache/apache-service.yml
# Tomcat kubernetes base
 - kustomize-base/kubernetes-objects/tomcat/tomcat-hr-ingress.yml
 - kustomize-base/kubernetes-objects/tomcat/tomcat-service.yml
 - kustomize-base/kubernetes-objects/tomcat/tomcat-addressbook-ingress.yml

configMapGenerator:
- name: users-map
  files:
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/users/191-users.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/users/190-user-administrator.xml
- name: pio-map
  files:
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/998-task-HR-livesync.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/180-orgs.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/160-roles.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/200-Certify-campaign.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/161-archetypes.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/152-openldap.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/950-HR-import.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/154-LDAP-import-dry-run.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/171-DefaultUserTemplate.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/170-orgs-objectTemplate.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/153-hr.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/001-system-configuration.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/999-LDAP-live-sync.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/151-addressbook.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/300-service-licencedService.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/301-collection-licencedServiceCollection.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/302-dashboard-licencesDashboard.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/201-task-User-Recomputation-Simulation-definition.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/202-task-User-Recomputation-definition.xml
    - kustomize-base/renaissance-demo-config/midpoint/post-initial-objects/other-pio/940-Task-Addressbook-accounts-import.xml
- name: extension-map
  files:
    - kustomize-base/renaissance-demo-config/midpoint/extension-schema/extension-electra.xsd
- name: hr-map
  files:
    - kustomize-base/renaissance-demo-config/hr/midpoint-source.csv
- name: hr-script-map
  files:
    - kustomize-base/renaissance-demo-config/hr/hr.sh
- name: login-page-map
  files:
    - kustomize-base/renaissance-demo-config/midpoint/login-page/addLoginPage.sh
    - kustomize-base/renaissance-demo-config/midpoint/login-page/AbstractPageLogin.html
- name: ldap-init-map
  files:
    - kustomize-base/renaissance-demo-config/ldap/sssvlv.ldif
    - kustomize-base/renaissance-demo-config/ldap/baseEntry.ldif
    - kustomize-base/renaissance-demo-config/ldap/ppolicy.ldif
    - kustomize-base/renaissance-demo-config/ldap/acl.ldif
- name: ldap-dynschema-map
  files:
    - kustomize-base/renaissance-demo-config/ldap/dyngroup.schema
- name: addressbook-script-map
  files:
    - kustomize-base/renaissance-demo-config/addressbook/addressbook.sh
- name: apache-map
  files:
    - kustomize-base/renaissance-demo-config/apache/httpd.conf
- name: tomcat-map
  files:
    - kustomize-base/renaissance-demo-config/tomcat/server.xml
