= Kubernetes - Midpoint live demo
:toc:
:toclevels: 4

This project contains files related to the midPoint live demo. In the `kustomize-base-directory` there are kubernetes objects and renaissance demo config files located. In `kustomize-env-config`, a certificate and variables for the demo environment are stored. These variables are configured by the setup script and then used by `kustomize` for replacing field values in kubernetes objects.

== Requirements

=== Operating system running the setup script
The setup script is primarily developed for Linux systems, but it can also run on Windows with WSL.

[NOTE]
When using Windows with WSL please make sure that you have the correct kubectl configuration in the WSL environment. If not, please install kubectl in the WSL environment and copy your Windows kubectl configuration to the WSL environment. Alternatively, you can replace `kubectl` in the setup script with a path to kubectl.exe.

=== K8s cluster
This demo is primarily intended for usage with the original k8s cluster. But it should also work with MicroK8s and Minikube clusters.

[NOTE]
When using the MicroK8s cluster please make sure that the kubectl command points to the MicroK8s cluster or replace `kubectl` in the setup script with `microk8s kubectl`.

[NOTE]
When using the Minikube cluster please make sure that you have installed the ingress controller, if not here is a guide on how you can enable it https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#enable-the-ingress-controller

== Usage

This readme will provide you with a guide to successfully deploy the midPoint demo on your own kubernetes cluster. You can find more information about the midPoint demo (for example, a walkthrough or implementation details) here: https://docs.evolveum.com/midpoint/demo/.

This guide is composed of three steps:
1. Setting up a certificate for our environment.
2. Running the startup script.
3. Following a walkthrough of the environment.

[NOTE]
When you don't have an available kubernetes cluster you can head to https://demo.evolveum.com/ where the midPoint demo is deployed and available to everyone.

{empty}1. Creating a certificate

[NOTE]
A basic certificate is available as default, but it is highly recommended to use your own certificate. The default address is `demo.example.com`.

[NOTE]
For a quick test solution you can generate your own certificate, though it is not recommended:

[source,bash]
----
openssl req -new -sha256 -newkey rsa:2048 -keyout tls.key -nodes -subj "/CN=test CA" | openssl x509 -req \
-signkey tls.key -out tls.crt -days 3650 -sha256 -extfile <(cat <<EOF
basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage = digitalSignature, nonRepudiation, keyEncipherment
subjectAltName = DNS:localhost, DNS:localhost.localdomain,DNS:*.localdomain, IP:127.0.0.1
extendedKeyUsage = serverAuth
EOF
)

openssl x509 -in tls.crt -text -noout
----

[NOTE]
It is better to make a trusted certificate with https://letsencrypt.org/

[NOTE]
To access midPoint using your private domain name, you must set up the name-to-IP-address mapping in the DNS. Alternatively, you can edit your `/etc/hosts` file.

[NOTE]
When using your own certificate please run this command to generate a YAML secret. Then use `-c` flag with startup script to use this certificate in demo enviroment and `-a` flag for custom host.

[source,bash]
----
kubectl create secret tls --dry-run=client -o yaml -n <NAMESPACE> <SECRET-NAME> --cert=tls.crt --key=tls.key
----

{empty}2. Running midpoint-live-demo-setup.sh

This script applies to your demo environment. You can change the default certificate`, namespace, ingressClass name or host for ingresses. You can do this by using these flags:

|===
|Flag |Description |Default value
|-n
|Custom namespace
|mp-demo

|-c
|Custom yaml certificate for ingresses. PLEASE USE THE SAME NAME FOR THE FILE AND THE KUBERNETES OBJECT
|cert-mp-demo (created by startup script)

|-a
|Custom host for ingresses. Please be aware that the default certificate does only work with the default host
|demo.example.com

|-i
|Custom ingressClass name. Make sure that you do have ONE default ingressClass or use this option to set a custom one.
|Default on your machine (one with annotation ingressclass.kubernetes.io/is-default-class: true).
|===

{empty}3. Wait for midPoint to start and then head to https://docs.evolveum.com/midpoint/demo/#walkthrough for walkthrogh of midPoint demo enviroment.

