= Kubernetes - Midpoint live demo
:toc:
:toclevels: 4

This location contain files related to the Midpoint live demo.

To successfully deploy midpoint live demo installation you must follow these steps:

1. Setup nfs on node:

[source,bash]
====
apt-get install nfs-common

cat << EOF >>/etc/systemd/resolved.conf
#[Resolve]
DNS=10.96.0.10
Domains=~cluster.local
EOF
====

[NOTE]
*nfs-common* is the name of the package on the debian based distribution (including ubuntu) with the necessary NFS mount support.
Once this package is available on the system the kubernetes can use natively NFS in volume definition.

[NOTE]
To have resolvable cluster's FQDN it is needed to let the node's system know where is the DNS server located.
Without this information the node is resolving using external DNS servers which have no information about cluster's domain.
10.96.0.10 is IP address of cluster dns server. Your may be different.

2. Create certificate:

[NOTE]
Basic certificate is available as default but it is highly recommended to use your own certificate. Default address is demo.example.com, when using your own certificate change addresses in ingress objects.

[NOTE]
For quick test solution you can generate your own certificate though it is not recommended:

openssl req -new -sha256 -newkey rsa:2048 -keyout tls.key -nodes -subj "/CN=test CA" | openssl x509 -req \
-signkey tls.key -out tls.crt -days 3650 -sha256 -extfile <(cat <<EOF
basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage = digitalSignature, nonRepudiation, keyEncipherment
subjectAltName = DNS:localhost, DNS:localhost.localdomain,DNS:*.localdomain, IP:127.0.0.1
extendedKeyUsage = serverAuth
EOF
)

openssl x509 -in tls.crt -text -noout

[NOTE]
It is better to make trusted certificate with https://letsencrypt.org/

[NOTE]
In order to access midPoint using your private domain name you must setup the name-to-IP-address mapping in the DNS. Alternatively, you can edit your /etc/hosts file.

3. Run midpoint-live-demo-setup.sh


For more information regarding midPoint demo please see https://docs.evolveum.com/midpoint/demo/
