apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: demo-test.k8s.evolveum.com
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: demo-test.k8s.evolveum.com
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    - op: replace
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "Force=true,Replace=true"
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: mp.*

resources:
  - ../../kustomize-base
  - network-policy.yml

