apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: demo-dev.e
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: demo-dev.e
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    - op: replace
      path: /spec/tls/0/secretName
      value: demo-dev-tls
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: any
      annotations:
        cert-manager.io/cluster-issuer: ca-e
        cert-manager.io/private-key-algorithm: ECDSA
        cert-manager.io/private-key-size: "256"
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
- patch: |-
    - op: replace
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "Force=true,Replace=true"
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: mp.*

resources:
  - ../../kustomize-base
  - network-policy.yml
