apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../kustomize-base

replacements:
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ingress_host
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host

resources:
  - network-policy.yml

configMapGenerator:
- name: config
  behavior: merge
  literals:
  - ingress_host=demo-test.k8s.evolveum.com
  options:
    disableNameSuffixHash: true
